[WIP] Add slang package
SymbiFlow/conda-packages pull request #43
Opened 2019-10-04 12:01 UTC by piotr-binkowski

Aim of this PR is to create [Slang](https://github.com/MikePopoloski/slang) conda package for use in SymbiFlow/sv-tests#183.

Slang uses features from C++17 which require at least gcc8 which is not available via `conda` or from default `apt` repositories. Correct gcc version is obtained from [ppa repository mentioned on Ubuntu wiki](https://wiki.ubuntu.com/ToolChain#PPA_packages)

2019-10-05 00:15 UTC, mithro commented
Conda has `x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0` which should support `C++17`?

2019-10-05 00:17 UTC, mithro commented
https://en.cppreference.com/w/cpp/compiler_support#cpp17 -- It says `GCC 7` is add the features?

2019-10-07 07:11 UTC, piotr-binkowski commented
`GCC 7` has only partial support for `std::filesystem` from C++17 via `std::experimental::filesystem` and things like `lexically_proximate` seem to be missing and only work in `GCC 8`

2019-10-10 21:12 UTC, mithro approved these changes

2019-10-10 21:13 UTC, mithro requested changes
Need to figure out if using gcc from the system is going to break anything....

2019-10-11 06:48 UTC, piotr-binkowski commented
I've added a patch that makes the output binaries static which should take care of any potential dynamic library incompatibilities caused by using system gcc.

2019-10-14 00:35 UTC, mithro approved these changes
LGTM.

2019-10-14 05:55 UTC, merged